spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: rahasia
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
resilience4j.ratelimiter:
  instances:
    orderService:
      limitForPeriod: 100
      limitRefreshPeriod: 4s
      timeoutDuration: 10s
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
